security:
    role_hierarchy:
      ROLE_ADMIN: [ ROLE_USER ]

    encoders:
        Symfony\Component\Security\Core\User\User: 'bcrypt'

    providers:
        memory:
          memory:
            users: ~

        chain_provider:
          chain:
              providers: ['memory']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/v1/login
            stateless: true
            anonymous: true
            provider: chain_provider
            json_login:
                check_path:               /api/v1/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        doc:
            pattern: ^/api/v1/doc
            anonymous: true
            provider: chain_provider

#        api:
#            pattern:   ^/api/v1
#            stateless: true
#            provider: chain_provider
#            guard:
#                authenticators:
#                    - lexik_jwt_authentication.jwt_token_authenticator


        main:
            anonymous: lazy
            provider: chain_provider

    access_control:
        - { path: ^/api/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/doc,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/v1,       roles: ROLE_USER }